# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authen', '0002_auto_20160308_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128)),
                ('introduction', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('topic_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('involved_type', models.IntegerField()),
                ('occurence_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('upvote_count', models.IntegerField(default=0)),
                ('downvote_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_author', to='authen.ForumUser')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('content', models.TextField()),
                ('click_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('reply_count', models.IntegerField(default=0)),
                ('last_replied_time', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_author', to='authen.ForumUser')),
                ('last_replied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_reply_author', to='authen.ForumUser')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node', to='forum.Node')),
            ],
        ),
        migrations.AddField(
            model_name='reply',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='forum.Topic'),
        ),
        migrations.AddField(
            model_name='notification',
            name='involved_reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_reply', to='forum.Reply'),
        ),
        migrations.AddField(
            model_name='notification',
            name='involved_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_topic', to='forum.Topic'),
        ),
        migrations.AddField(
            model_name='notification',
            name='involved_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_user', to='authen.ForumUser'),
        ),
        migrations.AddField(
            model_name='notification',
            name='trigger_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_user', to='authen.ForumUser'),
        ),
        migrations.AddField(
            model_name='collect',
            name='collect_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_collect', to='forum.Topic'),
        ),
        migrations.AddField(
            model_name='collect',
            name='collect_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_collect', to='authen.ForumUser'),
        ),
    ]
