# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20160309_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='last_replied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_reply_author', to='authen.ForumUser'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='last_replied_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
