# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 10:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='/images')),
                ('introduce', models.CharField(blank=True, max_length=128)),
                ('fortune', models.IntegerField(default=42)),
                ('updated', models.DateTimeField(default=datetime.datetime(2016, 3, 8, 10, 41, 49, 188367, tzinfo=utc))),
                ('website', models.URLField(blank=True, unique=True)),
                ('github', models.URLField(blank=True, unique=True)),
                ('douban', models.URLField(blank=True, unique=True)),
                ('weibo', models.URLField(blank=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
