# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 10:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumuser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 8, 10, 42, 1, 855722, tzinfo=utc)),
        ),
    ]
