# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 06:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_auto_20160308_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumuser',
            name='douban',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 9, 6, 46, 59, 417580, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='weibo',
            field=models.URLField(blank=True),
        ),
    ]
